### ISSUE TITLE
Can´t enable Addon

### ISSUE THREAD

**Issue by Consalv0** [keyhom/io_scene_cgf#1]
In Blender 2.80

When trying to enable the addon this error is shown:
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Consalvo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_scene_cgf\__init__.py", line 31, in <module>
    from bpy_extras.io_utils import (
ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy_extras\io_utils.py)`

**Comment by keyhom** [comment]
Blender 2.8 is not yet support.

**Comment by Mortecha** [comment]
@keyhom, I appreciate the work you've done on this so far, any intentions of returning to this project and getting it all updated and running again?
