### ISSUE TITLE
Can't install, Pyffi unable to be located, unspecified path

### ISSUE THREAD

**Issue by Mortecha** [keyhom/io_scene_cgf#2]
```
C:\Users\samke\Development\io_scene_cgf>python setup.py
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    run()
  File "setup.py", line 61, in run
    shutil.copytree(os.path.join(f, 'pyffi'), os.path.join(build_root, f), ignore=lambda  srcs, names: '__pycache__')
  File "C:\Python38\lib\shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'pyffi\\pyffi'
```

**Comment by Cosmic-Goat** [comment]
Did you make sure to pull the Pyffi submodule?:
```bash
git submodule init
git submodule update
python setup.py
```
